services:
  mongo:
    image: mongo:6
    container_name: mongo
    networks: [mynet]
    restart: always

  backend:
    image: 186091750343.dkr.ecr.us-west-2.amazonaws.com/backend-app:latest
    container_name: backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
    networks: [mynet]
    restart: always
    expose:
      - "8085"

networks:
  mynet:
