version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo-container
    ports:
      - "27017:27017"
    networks:
      - mynetwork

  backend:
    image: backend-app
    container_name: express-app
    environment:
      - MongoURI=mongodb://mongo:27017/mydb # ✅ Usa el nombre del servicio en lugar de la IP
    ports:
      - "8085:8085"
    depends_on:
      - mongo
    networks:
      - mynetwork

networks:
  mynetwork:
