# Usar la imagen oficial de MongoDB
FROM mongo:6

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /data/db

# Exponer el puerto de MongoDB
EXPOSE 27017

# Comando para ejecutar MongoDB
CMD ["mongod"]